classDiagram
direction LR

RuntimeException <|-- TokenExpiredException
GraphQLMutationResolver <|-- AliasMutation
GraphQLQueryResolver <|-- AliasQuery
GraphQLMutationResolver <|-- UserMutation
GraphQLQueryResolver <|-- UserQuery
GraphQLMutationResolver <|-- BlackListMutation
GraphQLQueryResolver <|-- BlackListQuery
GraphQLMutationResolver <|-- AliasSuggestionMutation
GraphQLQueryResolver <|-- AliasSuggestionQuery
JpaRepository <|-- AliasRepository
JpaRepository <|-- UserRepository
webSecurityConfigurerAdapter <|-- SecurityConfig


AliasService <|.. AliasServiceImp
UserService <|.. UserServiceImp
blackListService <|.. blackListServiceImp
aliasSuggestionService <|.. aliasSuggestionServiceImp

AliasRepository <-- AliasService
UserRepository <-- UserService
aliasSuggestionRepository <-- aliasSuggestionService
blackListRepository <-- blackListService


SecurityGraphQLAspect <.. AdminSecured
SecurityGraphQLAspect <.. Unsecured
SecurityGraphQLAspect ..> TokenExpiredException

Alias_Database *-- Alias
User_DB *-- User
aliasSuggestion_DB *-- aliasSuggestion

AliasMutation --> AliasService
AliasQuery --> AliasService
UserMutation --> UserService
UserQuery --> UserService
AliasSuggestionQuery --> aliasSuggestionService
AliasSuggestionMutation --> aliasSuggestionService
BlackListQuery --> blackListService
BlackListMutation --> blackListService

Alias_Database <.. AliasDataSourceConfig : Repository accesses and manipulates data
AliasDataSourceConfig <.. AliasRepository
User_DB <.. UserDataSourceConfig : Repository accesses and manipulates data
UserDataSourceConfig <.. UserRepository
aliasSuggestion_DB <.. aliasSuggestionDataSourceConfig : Repository accesses and manipulates data
aliasSuggestionDataSourceConfig <.. aliasSuggestionRepository
blackLiast_DB <.. blackListDataSourceConfig : Repository accesses and manipulates data
blackListDataSourceConfig <.. blackListRepository

AdminSecured <.. UserQuery
Unsecured <.. UserQuery
AdminSecured <.. UserMutation
Unsecured <.. UserMutation
AdminSecured <.. AliasQuery
Unsecured <.. AliasQuery
AdminSecured <.. AliasMutation
Unsecured <.. AliasMutation

Main <.. SecurityConfig : defaul access settings

AdminSecured ..> SecurityGraphQLAspect
Unsecured ..> SecurityGraphQLAspect

AliasQuery <.. AliasSchema
AliasMutation <.. AliasSchema
BlackListMutation <.. AliasSchema
BlackListQuery <.. AliasSchema
AliasSuggestionMutation <.. AliasSchema
AliasSuggestionQuery <.. AliasSchema



UserQuery <.. UserSchema    
UserMutation <.. UserSchema


class RuntimeException

class TokenExpiredException


class AliasService{
<<interface>>
}

class AliasServiceImp{
@Service
}

class GraphQLMutationResolver 

class AliasMutation{
+addAlias(Alias alias)
}

class UserMutation {
    login(ID-Token)
}

class GraphQLQueryResolver

class UserQuery {
    findUser(name) : User
    +searchMapObject(searchString) : mapID
}

class AliasSuggestionQuery {
    +showAliasSuggestions(mapID) : List<aliasSuggestion>
}

class AliasSuggestionMutation {
    +suggestAlias(mapID, userName)
    +evaluateAliasSuggestion(aliasSuggestion, userName)
}

class BlackListMutation {
    +addToBlacklist(String)
}

class BlackListQuery {
    isBanned(String)
}

class AliasQuery{
+findAllAlias(int MapID)
}


class SecurityConfig{
+configure()
}

class AdminSecured{
<<interface>> 
}

class Unsecured{
<<interface>> 
}

class SecurityGraphQLAspect{
@Aspect
@Component
@Order(1)
+doSecurityCheck()
+doAdminSecurityCheck()
}



class User{
@Entity
@Getter
@Setter
@Data
@Id
-id: long
@Column
-name: String
Collection<? extends GranedAuthority>
}


class Alias{
@Entity
@Getter
@Setter
@Data
@Table
@Id
-id: long
@Column
-name: String
@Column
-mapID
}

class aliasSuggestion

class AliasDataSourceConfig{ 
@Configuration
@EnableTransactionManagement
@EnableJpaRepsitories
+AliasDataSourceProperties():DataSourceProperties
+AliasDataSourceProperties():DataSource
+AliasEntityManagerFactory(EntityManagerFactoryBuilder builder):LocalContainerEntityManagerFactoryBean 
+AliasTransactionManager(LocalContainerEntityManagerFactoryBean):PlatformTransactionManager 
}  

class UserDataSourceConfig{ 
@Configuration
@EnableTransactionManagement
@EnableJpaRepsitories
+UserDataSourceProperties():DataSourceProperties
+UserDataSourceProperties():DataSource
+UserEntityManagerFactory(EntityManagerFactoryBuilder builder):LocalContainerEntityManagerFactoryBean 
+UserTransactionManager(LocalContainerEntityManagerFactoryBean):PlatformTransactionManager 
}

class blackListDataSourceConfig{ 
@Configuration
@EnableTransactionManagement
@EnableJpaRepsitories
+UserDataSourceProperties():DataSourceProperties
+UserDataSourceProperties():DataSource
+UserEntityManagerFactory(EntityManagerFactoryBuilder builder):LocalContainerEntityManagerFactoryBean 
+UserTransactionManager(LocalContainerEntityManagerFactoryBean):PlatformTransactionManager 
}

class aliasSuggestionDataSourceConfig{ 
@Configuration
@EnableTransactionManagement
@EnableJpaRepsitories
+UserDataSourceProperties():DataSourceProperties
+UserDataSourceProperties():DataSource
+UserEntityManagerFactory(EntityManagerFactoryBuilder builder):LocalContainerEntityManagerFactoryBean 
+UserTransactionManager(LocalContainerEntityManagerFactoryBean):PlatformTransactionManager 
}

class blackListService
class blackListServiceImp

class aliasSuggestionService
class aliasSuggestionServiceImp


class webSecurityConfigurerAdapter

class JpaRepository

class AliasRepository

class Alias_Database{
Alias_Database : External_Database
}

class UserService{
<<interface>>
}

class UserServiceImp{
String authorizationKey
Algorithm algorithm
+authenticate(HttpServletRequest):HttpServletResponse 
+getUser()
-addUser()
}

class UserRepository
class aliasSuggestionRepository
class blackListRepository

class User_DB
class aliasSuggestion_DB
class blackLiast_DB


class AliasSchema
class UserSchema

class Main {
    @SpringBootApplication
    @EnableAspectJAutoProxy 
        +main(args)
}